# This is the SimpleCoins configuration file.
# 
# Here you can configure EVERY aspect of the plugin.
# This includes the name of the coins (default is Coins), every message
# 
# 
#
#
# The name of your currency
CoinsName: Coins

# Database Connection Settings
Database:
  # Should we use a MySQL Database instead of a local file?
  UseSQL: false
  
  # Database Host
  Host: localhost
  
  # Database Port
  Port: 3306
  
  # Database in which the table will be created
  DatabaseName: minecraft
  
  # The username to connect with
  Username: username
  
  # The password to authenticate the user
  Password: password