name: SimpleCoins
version: @VERSION@
main: de.axelrindle.simplecoins.SimpleCoins
depend: [PocketKnife]
softdepend: [Vault]
website: http://dev.bukkit.org/projects/simplecoins/
commands:
  simplecoins:
    description: "Manage a Player's coin account."
    usage: /simplecoins
    aliases: [sc]
    permission: simplecoins.use
