name: SimpleCoins
version: 0.4
main: de.lalo5.simplecoins.SimpleCoins
softdepend: [Vault]
load: startup
website: http://dev.bukkit.org/projects/simplecoins/
commands:
  sc:
    description: "Manage a Player's coin account."
    usage: /sc
    aliases: [simplecoins]
    permission: simplecoins.use
