name: SimpleCoins
version: @VERSION@
main: de.axelrindle.simplecoins.SimpleCoins
depend: [PocketKnife]
softdepend: [PlaceholderAPI, Vault]
website: http://dev.bukkit.org/projects/simplecoins/
commands:
  simplecoins:
    usage: /simplecoins
    aliases: [sc]
    permission: simplecoins.use
