name: SimpleCoins
version: 1.0.0
main: de.lalo5.simplecoins.SimpleCoins
softdepend: [Vault]
website: http://dev.bukkit.org/bukkit-plugins/simplecoins/
commands:
  sc:
    description: Main command
    usage: /sc