name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: minecraft
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build project
      run: ./gradlew build -x test
    - name: Run tests
      run: ./gradlew test
      env:
        MYSQL_TEST_HOST: localhost
        MYSQL_TEST_PORT: ${{ job.services.mysql.ports[3306] }}
        MYSQL_TEST_DB: minecraft
        MYSQL_TEST_USER: root
        MYSQL_TEST_PASSWORD: root
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: Test Reports
        path: build/reports
